# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r:
    - release
    - devel

sudo: false
cache: packages
warnings_are_errors: false
bioc_packages:
    - BiocStyle

os: linux
dist: trusty

r_packages:
  - covr
after_success:
  - Rscript -e 'covr::codecov()'
